HW-297: Sets settings when installing Mosaico extension
veda-consulting/uk.co.vedaconsulting.mosaico pull request #151
Opened 2017-05-10 11:39 UTC by meladawy

Set default layout to 'bootstrap-wizard' using Mosaico settings file instead of using cv command

2017-05-10 11:45 UTC, omarabuhussein requested changes

2017-05-10 11:45 UTC, omarabuhussein commented on mosaico.php
> +  _mosaico_civicrm_install_settings();
it is better to keep the order like this : 

```php
_mosaico_civicrm_install_settings();

_mosaico_civix_civicrm_postInstall();
```

2017-05-10 11:49 UTC, omarabuhussein approved these changes

2017-05-11 09:30 UTC, guanhuan commented
Looks good now. Please merge.

2017-05-11 10:29 UTC, merged

2017-05-13 19:07 UTC, totten commented
IMHO, this PR was still incorrectly written. See point #2 from the previous discussion in https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/146 -- the aim is for `auto` to stay pegged to mean "the default on new installations"

2017-05-15 10:27 UTC, meladawy commented
Hey @totten, Sorry I missed this one as its got merged before we complete our discussion. I'll update this PR later today. Thanks!